/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#include <stdio.h> 
#include <time.h> 
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xweisd00NetSnmpMIB.h"

static char login[8] = "xweisd00";
/*    TIME     */
time_t rawtime;
struct tm *tmp;
char buffer[21];

/** Initializes the xweisd00NetSnmpMIB module */
void
init_xweisd00NetSnmpMIB(void)
{
    const oid nstAgentLoginObject_oid[] = { 1,3,6,1,3,22,1 };
    const oid nstAgentDateTimeObject_oid[] = { 1,3,6,1,3,22,2 };
    const oid nstAgentReadWriteObject_oid[] = { 1,3,6,1,3,22,3 };
    const oid nstAgentInputObject_oid[] = { 1,3,6,1,3,22,4 };

  DEBUGMSGTL(("xweisd00NetSnmpMIB", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("nstAgentLoginObject", handle_nstAgentLoginObject,
                               nstAgentLoginObject_oid, OID_LENGTH(nstAgentLoginObject_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("nstAgentDateTimeObject", handle_nstAgentDateTimeObject,
                               nstAgentDateTimeObject_oid, OID_LENGTH(nstAgentDateTimeObject_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("nstAgentReadWriteObject", handle_nstAgentReadWriteObject,
                               nstAgentReadWriteObject_oid, OID_LENGTH(nstAgentReadWriteObject_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("nstAgentInputObject", handle_nstAgentInputObject,
                               nstAgentInputObject_oid, OID_LENGTH(nstAgentInputObject_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_nstAgentLoginObject(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     &login,
                                     sizeof(&login));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_nstAgentLoginObject\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_nstAgentDateTimeObject(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
	
	time( &rawtime );
	tmp = localtime( &rawtime );
	strftime(buffer,21,"%Y-%m-%dT%H:%M:%SZ", tmp);

    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                      &buffer,
				      sizeof(buffer)-1);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_nstAgentDateTimeObject\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_nstAgentReadWriteObject(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

       /* case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                      XXX: a pointer to the scalar's data */
                                     /* XXX: the length of the data in bytes );*/
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            /* if (XXX if malloc, or whatever, failed: )*/ {
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            /* XXX: perform the value change here */
            /*if ( XXX: error? )*/ {
           /*     netsnmp_set_request_error(reqinfo, requests, some error );*/
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
           /* if ( XXX: error? ) */{
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            /* if (XXX: error? )*/ {
                /* try _really_really_ hard to never get to this point */
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_nstAgentReadWriteObject\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_nstAgentInputObject(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            /*snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                      XXX: a pointer to the scalar's data */
                                     /* XXX: the length of the data in bytes );*/

            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_nstAgentInputObject\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
