/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef XWEISD00NETSNMPMIB_H
#define XWEISD00NETSNMPMIB_H

/* function declarations */
void init_xweisd00NetSnmpMIB(void);
Netsnmp_Node_Handler handle_nstAgentLoginObject;
Netsnmp_Node_Handler handle_nstAgentDateTimeObject;
Netsnmp_Node_Handler handle_nstAgentReadWriteObject;
Netsnmp_Node_Handler handle_nstAgentInputObject;

#endif /* XWEISD00NETSNMPMIB_H */
